markdown: rdiscount
permalink: /:year/:month/:title/
url: http://www.mtcle.tk
production_url : http://www.mtcle.tk
author: mtcle
feedburner : mtcle
pygments: true
paginate: 24
safe: true
lsi: false
source: /home/mtcle/blog
pygments: true
BASE_PATH : http://www.mtcle.tk
ASSET_PATH : http://www.mtcle.tk
archive_path: /blog/archive.html
categories_path : /blog/categories.html
tags_path : /blog/tags.html
atom_path : /blog/atom.xml
rss_path : /blog/rss.xml
