markdown: rdiscount
permalink: /:year/:month/:title/
url: http://mtcle.tk
author: mtcle
feedburner : mtcle
pygments: true
paginate: 24
safe: true
lsi: false
pygments: true
BASE_PATH : http://mtcle.tk/blog
production_url : http://mtcle.tk
archive_path: /blog/archive.html
categories_path : /blog/categories.html
tags_path : /blog/tags.html
atom_path : /blog/atom.xml
rss_path : /blog/rss.xml
