markdown: rdiscount
permalink: /:year/:month/:title/
url: http://mtcle.github.io/blog
production_url : http://mtcle.github.io/blog
author: mtcle
feedburner : mtcle
pygments: true
paginate: 24
safe: true
lsi: false
source: /home/mtcle/blog
pygments: true
BASE_PATH : http://mtcle.github.io/blog
ASSET_PATH : http://mtcle.github.io/blog
production_url : http://mtcle.github.io/blog
archive_path: /blog/archive.html
categories_path : /blog/categories.html
tags_path : /blog/tags.html
atom_path : /blog/atom.xml
rss_path : /blog/rss.xml
