markdown: rdiscount
permalink: /:year/:month/:title/
url: http://www.mtcle.tk
production_url : http://www.mtcle.tk
author: mtcle
feedburner : mtcle
pygments: true
paginate: 24
safe: true
lsi: false
pygments: true
BASE_PATH : http://www.mtcle.tk
ASSET_PATH : http://www.mtcle.tk

